version: '3.7'
services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=pizza
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=pizzashop
    volumes:
      - ./docker/volumes/postgres/:/var/lib/postgresql/

